// Hand-written Wails bindings shim (normally generated by the Wails CLI).
// window.go.main.App is injected into the webview by the Go binary at startup.
const app = () => window.go?.main?.App ?? {}

export function Submit(arg1) { return app().Submit(arg1) }
export function StartListening() { return app().StartListening() }
export function StopListening() { return app().StopListening() }
export function Status() { return app().Status() }
export function CancelSpeech() { return app().CancelSpeech() }
