// Hand-written Wails runtime shim (normally generated by the Wails CLI).
// window.runtime is injected into the webview by the Go binary at startup.
const rt = () => window.runtime ?? {
  EventsOn: () => () => {},
  EventsOff: () => {},
  EventsEmit: () => {},
}

export function EventsOn(eventName, callback) {
  return rt().EventsOn(eventName, callback)
}
export function EventsOff(...eventNames) {
  rt().EventsOff(...eventNames)
}
export function EventsEmit(eventName, ...data) {
  rt().EventsEmit(eventName, ...data)
}
